Traceback (most recent call last):
  File "main.py", line 183, in <module>
    train(cfg)
  File "main.py", line 118, in train
    train_detector(model, datasets, cfg, distributed=False, validate=True,meta=meta)
  File "/opt/ml/level2_objectdetection-cv-11/UniverseNet/mmdet/apis/train.py", line 306, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/opt/ml/level2_objectdetection-cv-11/UniverseNet/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/opt/ml/level2_objectdetection-cv-11/UniverseNet/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/opt/ml/level2_objectdetection-cv-11/UniverseNet/mmdet/models/detectors/single_stage.py", line 82, in forward_train
    x = self.extract_feat(img)
  File "/opt/ml/level2_objectdetection-cv-11/UniverseNet/mmdet/models/detectors/single_stage.py", line 43, in extract_feat
    x = self.backbone(img)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/ml/level2_objectdetection-cv-11/UniverseNet/mmdet/models/backbones/swin_transformer_v2.py", line 807, in forward
    x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/ml/level2_objectdetection-cv-11/UniverseNet/mmdet/models/backbones/swin_transformer_v2.py", line 537, in forward
    x = blk(x, attn_mask)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/ml/level2_objectdetection-cv-11/UniverseNet/mmdet/models/backbones/swin_transformer_v2.py", line 380, in forward
    x = x + self.drop_path(self.norm2(self.mlp(x)))
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/mmcv/cnn/bricks/drop.py", line 48, in forward
    return drop_path(x, self.drop_prob, self.training)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/mmcv/cnn/bricks/drop.py", line 27, in drop_path
    output = x.div(keep_prob) * random_tensor.floor()
RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 31.75 GiB total capacity; 30.24 GiB already allocated; 11.50 MiB free; 30.27 GiB reserved in total by PyTorch)